# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Expose any ports if needed (not required for stdio)

# Use npm start to run the MCP server
CMD ["npm", "start"]
